import React from 'react';
import {
  StyleSheet,
  Dimensions,
} from 'react-native';
import { palette } from './palette';

const chosenFont = "../assets/fonts/AbhayaLibre-Bold.ttf" // or "Avenir"

const { width: SCREEN_WIDTH, height: SCREEN_HEIGHT } = Dimensions.get('window');

const convoStyles = StyleSheet.create({
  background: {
    flex: 1,
    width: '100%',
    height: '100%',
  },
  backButton: {
    position: 'absolute',
    top: SCREEN_HEIGHT * 0.05,
    left: SCREEN_WIDTH * 0.05,
    zIndex: 10,
  },
  container: {
    flex: 1,
    paddingTop: SCREEN_HEIGHT * 0.06,
    paddingHorizontal: 20,
    alignItems: 'center',
  },
  statusText: {
    fontSize: 20,
    fontFamily: chosenFont,
    color: palette.slate,
    margin: 8,
  },
  timerText: {
    fontSize: 30,
    fontFamily: chosenFont,
    color: palette.slate,
    fontWeight: '800',
    marginBottom: 20,
  },
  avatarsContainer: {
    alignItems: 'center',
    marginBottom: 10,
  },
  avatarSection: {
    alignItems: 'center',
    marginVertical: 5,
  },
  avatar: {
    width: 100,
    height: 100,
    borderRadius: 50,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 5,
  },
  avatarLetter: {
    fontSize: 48,
    color: palette.cream,
    fontWeight: '700',
  },
  nameText: {
    fontSize: 24,
    fontFamily: chosenFont,
    color: palette.slate,
    fontWeight: '600',
    marginBottom: 8,
  },
  statusIndicator: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  statusDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: palette.teal,
  },
  statusLabel: {
    fontSize: 14,
    fontFamily: chosenFont,
    color: palette.teal,
  },
  dividerLine: {
    width: 2,
    height: 60,
    backgroundColor: palette.cream + '40',
  },
  resourcesContainer: {
    flexDirection: 'row',
    gap: 16,
    marginTop: 10,
    marginBottom: 5,
  },
  resourceCard: {
    backgroundColor: palette.cream + '80',
    borderRadius: 16,
    padding: 9,
    width: SCREEN_WIDTH * 0.41,
    alignItems: 'center',
  },
  resourceIcon: {
    width: 48,
    height: 48,
    borderRadius: 24,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 12,
  },
  resourceIconText: {
    fontSize: 24,
  },
  resourceTitle: {
    fontSize: 16,
    fontFamily: chosenFont,
    color: palette.slate,
    textAlign: 'center',
    fontWeight: '500',
  },
  pauseHintText: {
    fontSize: 15,
    fontFamily: chosenFont,
    fontStyle: "italic",
    color: palette.teal,
    fontWeight: "400",
    margin: 8,
    marginTop: 20,
  },
  pauseButton: {
    backgroundColor: palette.slate,
    paddingVertical: 18,
    paddingHorizontal: 32,
    borderRadius: 30,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 12,
    width: SCREEN_WIDTH * 0.85,
    shadowColor: palette.shadow,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 6,
  },
  pauseButtonText: {
    fontSize: 18,
    fontFamily: chosenFont,
    color: palette.cream,
    fontWeight: '700',
  },
  container_pause: {
    flex: 1,
    paddingTop: SCREEN_HEIGHT * 0.05,
    paddingHorizontal: 20,
    paddingBottom: 20,
    alignItems: 'center',
  },
  statusText_pause: {
    fontSize: 18,
    fontFamily: chosenFont,
    color: palette.slate,
    marginBottom: 30,
    marginTop: 20,
    fontWeight: "900"
  },
  breatheCircle: {
    width: 140,
    height: 140,
    borderRadius: 70,
    backgroundColor: palette.slate,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 30,
    shadowColor: palette.slate,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.6,
    shadowRadius: 20,
    elevation: 10,
  },
  breatheText: {
    fontSize: 28,
    fontFamily: chosenFont,
    color: palette.cream,
    fontWeight: '600',
  },
  timerSection: {
    alignItems: 'center',
    marginBottom: 30,
  },
  timerLabel: {
    fontSize: 16,
    fontFamily: chosenFont,
    color: palette.lightBrown,
    marginBottom: 8,
  },
  timerText_pause: {
    fontSize: 48,
    fontFamily: chosenFont,
    color: palette.lightBrown,
    fontWeight: '700',
    marginBottom: 12,
  },
  breatheInstruction: {
    fontSize: 15,
    fontFamily: chosenFont,
    color: palette.lightBrown + 'CC',
    fontStyle: 'italic',
  },
  resourcesSection: {
    flex: 1,
    width: '100%',
    marginBottom: 20,
  },
  resourcesGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 16,
    justifyContent: "center",
  },
  resourceSubtitle: {
    fontSize: 15,
    marginTop: 4,
    fontFamily: chosenFont,
    color: palette.slate + 'AA',
    textAlign: 'center',
    lineHeight: 14,
  },
  resumeButton: {
    backgroundColor: palette.slate,
    paddingVertical: 16,
    paddingHorizontal: 32,
    borderRadius: 30,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 12,
    width: SCREEN_WIDTH * 0.85,
    shadowColor: palette.shadow,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 6,
  },
  resumeButtonText: {
    fontSize: 16,
    fontFamily: chosenFont,
    color: palette.cream,
    fontWeight: '700',
  },
});

export default convoStyles;